export const STUDENT_ICONS: Record<string, string> = {
  "kuku-drill": "✖️",
  "pref-quiz": "🗾",
  "fraction-basics-g2": "🍕",
  "fraction-addition-g3": "🍕",
  "fraction-equivalent-g4": "🍕",
  "fraction-common-denominator-g5": "🍕",
  "fraction-multiply-divide-g6": "🍕",
  "kanji-quiz-g5": "📖",
  "kanji-quiz-g6": "📖",
  "vocab-flashcards-g5": "🔤",
  "vocab-flashcards-g6": "🔤",
  "vocab-flashcards-jhs1": "🔤",
  "water-states-g4": "💧",
  "water-states-particle-jhs1": "💧",
  "visual-schedule": "🗓️",
  "visual-timer": "⏱️",
  "feelings-check": "😊",
  "communication-board": "🗣️",
  "social-story": "🤝",
  "expression-quiz": "🙂",
  "turn-taking": "🔁",
  "eye-tracking": "👀",
  "number-search": "🔢",
  "shape-match": "🔺",
};

export const DEFAULT_STUDENT_ICON = "⭐";
