export const STUDENT_ICONS: Record<string, string> = {
  "kuku-drill": "✖️",
  "pref-quiz": "🗾",
  "fraction-basics-g2": "🍕",
  "fraction-addition-g3": "🍕",
  "fraction-equivalent-g4": "🍕",
  "fraction-common-denominator-g5": "🍕",
  "fraction-multiply-divide-g6": "🍕",
  "kanji-quiz-g5": "📖",
  "kanji-quiz-g6": "📖",
  "vocab-flashcards-g5": "🔤",
  "vocab-flashcards-g6": "🔤",
  "vocab-flashcards-jhs1": "🔤",
  "water-states-g4": "💧",
  "water-states-particle-jhs1": "💧",
  "visual-schedule": "🗓️",
  "visual-timer": "⏱️",
  "feelings-check": "😊",
  "communication-board": "🗣️",
  "social-story": "🤝",
  "expression-quiz": "🙂",
  "turn-taking": "🔁",
  "eye-tracking": "👀",
  "number-search": "🔢",
  "shape-match": "🔺",
  "vocab-birthday-months-g5": "🎂",
  "vocab-town-directions-g5": "🏫",
  "vocab-summer-vacation-g6": "🏖️",
  "vocab-future-dreams-g6": "🌟",
  "length-basics-g2": "📏",
  "division-remainder-g3": "🔵",
  "percentage-basics-g5": "📊",
  "plant-growth-g3": "🌻",
  "circuit-basics-g3": "💡",
  "weather-temperature-g4": "🌤️",
  "trapezoid-area-g5": "🔷",
  "parallelogram-area-g5": "▱",
  "triangle-area-g5": "🔺",
  "polygon-angle-sum-g5": "🔶",
  "circle-area-g6": "⭕",
};

export const DEFAULT_STUDENT_ICON = "⭐";
